In [28]:

from pathlib import Path
import pandas as pd
import re
from IPython.display import display
DATA_DIR = Path(r"D:\SSAI trud\data3")
print("Dataset folder exists:", DATA_DIR.exists())
print("Dataset path:", DATA_DIR)

Dataset folder exists: True
Dataset path: D:\SSAI trud\data3

## 1. Load and inspect files

- Define the dataset folder and confirm that the data directory exists.
- Import the core libraries needed for reading, filtering, and displaying the data.
- This is the starting point for understanding the overall dataset structure.

In [29]:

def extract_participant_id(folder_name):
    # baraj broj vo imeto na folderot
    match = re.search(r"\d+", folder_name)
    # \d e bilo koja cifra
    return int(match.group()) if match else 0

# za site participants lista od DATA_DIR
# site sto se so participant
participant_dirs = [
    p for p in DATA_DIR.iterdir()
    if p.is_dir() and p.name.lower().startswith("participant")
]

# sortiraj gi po rastecki redosled
participant_dirs = sorted(participant_dirs, key=lambda p: extract_participant_id(p.name))

# br na participants
print("Number of participant folders:", len(participant_dirs))

print("First 10:", [p.name for p in participant_dirs[:10]])

print("Last 10:", [p.name for p in participant_dirs[-10:]])

Number of participant folders: 106
First 10: ['participant1', 'participant2', 'participant3', 'participant4', 'participant5', 'participant6', 'participant7', 'participant8', 'participant9', 'participant10']
Last 10: ['participant96', 'participant97', 'participant98', 'participant99', 'participant100', 'participant101', 'participant102', 'participant103', 'participant104', 'participant105']

## 2. Participant folders and IDs

- Collect all folders that belong to participants.
- Extract the numeric participant ID from each folder name.
- Sort the folders so the inspection follows a clean participant order.

In [3]:
#kakvi csv ima
top_level_csvs = list(DATA_DIR.glob("*.csv"))

print("CSV files:")
for f in top_level_csvs:
    print(f.name, round(f.stat().st_size / 1024, 2), "KB")

Top-level CSV files:
final_data_details.csv 2.81 KB
final_data_questionnaires.csv 18.39 KB

## 3. Top-level CSV overview

- List the CSV files stored directly inside the dataset folder.
- Check which global files are available before drilling into participant-level data.
- This helps separate dataset-wide tables from per-participant sensor files.

In [4]:
#razgleduvanje details i questionnaries
def read_csv_auto(path, nrows=None):
    return pd.read_csv(path, sep=None, engine="python", nrows=nrows)

details_path = DATA_DIR / "final_data_details.csv"
questionnaires_path = DATA_DIR / "final_data_questionnaires.csv"

details = read_csv_auto(details_path)
questionnaires = read_csv_auto(questionnaires_path)

print("details shape:", details.shape)
print("questionnaires shape:", questionnaires.shape)

details shape: (105, 8)
questionnaires shape: (105, 68)

## 4. Details and questionnaires

- Load the two main dataset tables: `final_data_details.csv` and `final_data_questionnaires.csv`.
- These tables are used to understand participant metadata and label-related information.
- Their shapes and columns show how the cleaned dataset is organized.

In [5]:
#pecatenje koloni 
print("DETAILS columns:")
print(details.columns.tolist())

print("\nQUESTIONNAIRES columns:")
print(questionnaires.columns.tolist())

DETAILS columns:
['ID', 'start_cal_time_h', 'start_cal_time_m', 'start_vid_time_h', 'start_vid_time_m', 'end_vid_time_h', 'end_vid_time_m', 'additional info']

QUESTIONNAIRES columns:
['ID', 'gender', 'age', 'slo_fluent', 'epil-hc', 'other_healthcon', 'good_vision', 'bad_hearing', 'facial_palsy-stroke', 'VR_experience', 'current_status', 'degree', 'group_job-sp', 'anxiety', 'inf_cons', 'video', 'feelof_presence_inVE', 'captivatedby_VE', 'real_VWorld', 'awareness_RWorld', 'issues_in_VR', 'stateEmpathy1a', 'stateEmpathy1b', 'stateEmpathy1c', 'valence1', 'arousal1', 'discomfort1', 'stateEmpathy2a', 'stateEmpathy2b', 'stateEmpathy2c', 'valence2', 'arousal2', 'discomfort2', 'stateEmpathy3a', 'stateEmpathy3b', 'stateEmpathy3c', 'valence3', 'arousal3', 'discomfort3', 'stateEmpathy4a', 'stateEmpathy4b', 'stateEmpathy4c', 'valence4', 'arousal4', 'discomfort4', 'stateValence', 'stateArousal', 'perspective-taking_points', 'perspective-taking_rate', 'online-simulation_points', 'online-simulation_rate', 'traitEmpathy_cog_points', 'traitEmpathy_cog_rate', 'emotion-contagion_points', 'emotion-contagion_rate', 'proximal-responsivity_points', 'proximal-responsivity_rate', 'peripheral-responsivity_points', 'peripheral-responsivity_rate', 'traitEmpathy_affec_points', 'traitEmpathy_affec_rate', 'Empathy1', 'Empathy2', 'Empathy3', 'Empathy4', 'Empathy_avg', 'Empathy_min', 'Arousal_RC']

In [6]:
#pregled koloni
display(details.head())
display(questionnaires.head())

,ID,start_cal_time_h,start_cal_time_m,start_vid_time_h,start_vid_time_m,end_vid_time_h,end_vid_time_m,additional info
0,1,14,1,14,5,14.0,36.0,work
1,2,13,6,13,10,13.0,38.0,work
2,3,14,11,14,15,14.0,35.0,work - without RC vid
3,4,13,9,13,13,13.0,34.0,work
4,5,14,18,14,22,14.0,47.0,work

,ID,gender,age,slo_fluent,epil-hc,other_healthcon,good_vision,bad_hearing,facial_palsy-stroke,VR_experience,...,peripheral-responsivity_rate,traitEmpathy_affec_points,traitEmpathy_affec_rate,Empathy1,Empathy2,Empathy3,Empathy4,Empathy_avg,Empathy_min,Arousal_RC
0,1,z,24,1,0,0,1,0,0,3,...,3.50,8.0,3,3.0,1.7,2.7,2.3,2.4,1.7,4.0
1,2,m,27,1,0,0,1,0,0,3,...,2.50,7.0,2,3.0,0.0,1.0,1.7,1.4,0.0,0.0
2,3,m,28,1,0,0,1,0,0,3,...,2.75,8.0,3,1.0,2.7,2.7,1.7,2.0,1.0,NaN
3,4,m,30,1,0,0,1,0,0,1,...,2.75,7.5,2,2.3,3.0,3.0,2.7,2.8,2.3,1.0
4,5,m,35,1,0,0,1,0,0,2,...,2.50,5.5,2,2.3,2.7,3.7,1.3,2.5,1.3,4.0

In [7]:
#naogjanje mozni vazni koloni 
keywords = [
    "participant", "subject", "user", "id",
    "video", "stimulus", "clip", "movie",
    "valence", "val",
    "arousal", "aro",
    "emotion",
    "time", "timestamp", "start", "end", "duration"
]

def find_matching_columns(df, keywords):
    matches = []
    for col in df.columns:
        col_lower = str(col).lower()
        if any(k in col_lower for k in keywords):
            matches.append(col)
    return matches

print("Possible important columns in DETAILS:")
print(find_matching_columns(details, keywords))

print("\nPossible important columns in QUESTIONNAIRES:")
print(find_matching_columns(questionnaires, keywords))

Possible important columns in DETAILS:
['ID', 'start_cal_time_h', 'start_cal_time_m', 'start_vid_time_h', 'start_vid_time_m', 'end_vid_time_h', 'end_vid_time_m']

Possible important columns in QUESTIONNAIRES:
['ID', 'gender', 'video', 'valence1', 'arousal1', 'valence2', 'arousal2', 'valence3', 'arousal3', 'valence4', 'arousal4', 'stateValence', 'stateArousal', 'emotion-contagion_points', 'emotion-contagion_rate', 'Arousal_RC']

In [13]:
#proveri participant 1 folder 
sample_participant = DATA_DIR / "participant1"

sample_files = list(sample_participant.glob("*.csv"))

print("Files in", sample_participant.name)
for f in sample_files:
    print(f.name, round(f.stat().st_size / (1024 * 1024), 2), "MB")

Files in participant1
3NVLIWA4.csv 341.96 MB
arousal_3NVLIWA4.csv 67.07 MB
breathingRate_3NVLIWA4.csv 71.89 MB
emgActivation_3NVLIWA4.csv 128.19 MB
expression_3NVLIWA4.csv 47.08 MB
facialActivation_3NVLIWA4.csv 57.5 MB
facialValence_3NVLIWA4.csv 39.54 MB
headMotion_3NVLIWA4.csv 0.0 MB
hrv_3NVLIWA4.csv 166.35 MB
valence_3NVLIWA4.csv 65.72 MB

## 5. Inspect participant CSV files

- Open one participant folder to see the sensor and annotation files inside it.
- Preview the first rows of each CSV to understand their schema.
- This reveals the structure of the raw per-participant data that will later be used for feature extraction.

In [30]:

def read_csv_auto(path, nrows=None):
    # ovie separatori
    separators = [",", ";", "\t"]
    encodings = ["utf-8-sig", "utf-8", "latin1"]

    for encoding in encodings:
        for sep in separators:
            try:
                # obid za citanje csv so tekovnite parametri
                df = pd.read_csv(
                    path,
                    sep=sep,
                    encoding=encoding,
                    nrows=nrows,
                    low_memory=False
                )

                if df.shape[1] > 1:
                    return df
            except Exception:
                pass

    # ako ne pomine niedna kombinacija, probaj najblaga verzija
    return pd.read_csv(
        path,
        sep=",",
        encoding="latin1",
        nrows=nrows,
        on_bad_lines="skip",
        low_memory=False
    )

In [15]:
#kje gi otvori prvite 5 reda od sekoj csv 
for f in sample_files:
    print("\n====================================")
    print("FILE:", f.name)
    
    df_sample = read_csv_auto(f, nrows=5)
    
    print("Shape:", df_sample.shape)
    print("Columns:")
    print(df_sample.columns.tolist())
    
    display(df_sample.head())

====================================
FILE: 3NVLIWA4.csv
Shape: (5, 2)
Columns:
['#Format/Version', 'CSV1.1.1']

         #Format/Version                                    CSV1.1.1
0       #File/Normalised                                          NO
1            #Time/Epoch                                        Unix
2           #File/Source  /opt/ml/processing/input_data/3NVLIWA4.dab
3      #Protocol/Version                                    MASK.1.7
4  #Emg/Config/Raw.hertz                                        1000

====================================
FILE: arousal_3NVLIWA4.csv
Shape: (5, 6)
Columns:
['Frame#', 'Time', 'Arousal/class', 'Arousal/probability', 'Imu/MotionIntensity', 'Ppg/QualityIndex']

,Frame#,Time,Arousal/class,Arousal/probability,Imu/MotionIntensity,Ppg/QualityIndex
0,1,1.703164e+09,0.0,0.59,0.066667,1.0
1,2,1.703164e+09,0.0,0.59,0.066667,1.0
2,3,1.703164e+09,0.0,0.59,0.066667,1.0
3,4,1.703164e+09,0.0,0.59,0.066667,1.0
4,5,1.703164e+09,0.0,0.59,0.066667,1.0

====================================
FILE: breathingRate_3NVLIWA4.csv
Shape: (5, 5)
Columns:
['Frame#', 'Time', 'BreathingRate', 'Ppg/QualityIndex', 'Imu/MotionIntensity']

   Frame#          Time  BreathingRate  Ppg/QualityIndex  Imu/MotionIntensity
0       1  1.703164e+09      13.102513               1.0             0.076923
1       2  1.703164e+09      13.102513               1.0             0.076923
2       3  1.703164e+09      13.102513               1.0             0.076923
3       4  1.703164e+09      13.102513               1.0             0.076923
4       5  1.703164e+09      13.102513               1.0             0.076923

====================================
FILE: emgActivation_3NVLIWA4.csv
Shape: (5, 6)
Columns:
['Frame#', 'Time', 'Emg/Amplitude/zygo/weighted', 'Emg/Amplitude/orbi/weighted', 'Emg/Amplitude/front/weighted', 'Emg/Amplitude/corr/weighted']

,Frame#,Time,Emg/Amplitude/zygo/weighted,Emg/Amplitude/orbi/weighted,Emg/Amplitude/front/weighted,Emg/Amplitude/corr/weighted
0,1,1.703164e+09,5.717594,4.750312,-1.614463,6.508871
1,2,1.703164e+09,5.719659,4.750435,-1.591675,6.511517
2,3,1.703164e+09,5.721805,4.750555,-1.566982,6.514346
3,4,1.703164e+09,5.724027,4.750674,-1.540306,6.517362
4,5,1.703164e+09,5.726322,4.750789,-1.511574,6.520566

====================================
FILE: expression_3NVLIWA4.csv
Shape: (5, 4)
Columns:
['Frame#', 'Time', 'Expression/Type', 'Expression/Intensity']

   Frame#          Time Expression/Type  Expression/Intensity
0       1  1.703164e+09         neutral                   0.0
1       2  1.703164e+09         neutral                   0.0
2       3  1.703164e+09         neutral                   0.0
3       4  1.703164e+09         neutral                   0.0
4       5  1.703164e+09         neutral                   0.0

====================================
FILE: facialActivation_3NVLIWA4.csv
Shape: (5, 3)
Columns:
['Frame#', 'Time', 'FacialActivation']

   Frame#          Time  FacialActivation
0       1  1.703164e+09          0.120368
1       2  1.703164e+09          0.120368
2       3  1.703164e+09          0.120368
3       4  1.703164e+09          0.120368
4       5  1.703164e+09          0.120368

====================================
FILE: facialValence_3NVLIWA4.csv
Shape: (5, 3)
Columns:
['Frame#', 'Time', 'FacialValence']

   Frame#          Time  FacialValence
0       1  1.703164e+09            0.0
1       2  1.703164e+09            0.0
2       3  1.703164e+09            0.0
3       4  1.703164e+09            0.0
4       5  1.703164e+09            0.0

====================================
FILE: headMotion_3NVLIWA4.csv
Shape: (2, 1)
Columns:
['headMotion']

   headMotion
0    3.000000
1    3.636364

====================================
FILE: hrv_3NVLIWA4.csv
Shape: (5, 9)
Columns:
['Frame#', 'Time', 'HRV/mean_hr', 'HRV/rr', 'HRV/sdnn', 'HRV/sdsd', 'HRV/rmssd', 'Imu/MotionIntensity', 'Ppg/QualityIndex']

,Frame#,Time,HRV/mean_hr,HRV/rr,HRV/sdnn,HRV/sdsd,HRV/rmssd,Imu/MotionIntensity,Ppg/QualityIndex
0,1,1.703164e+09,84.862385,707.027027,86.269999,117.184038,117.189306,0.066667,1.0
1,2,1.703164e+09,84.862385,707.027027,86.269999,117.184038,117.189306,0.066667,1.0
2,3,1.703164e+09,84.862385,707.027027,86.269999,117.184038,117.189306,0.066667,1.0
3,4,1.703164e+09,84.862385,707.027027,86.269999,117.184038,117.189306,0.066667,1.0
4,5,1.703164e+09,84.862385,707.027027,86.269999,117.184038,117.189306,0.066667,1.0

====================================
FILE: valence_3NVLIWA4.csv
Shape: (5, 6)
Columns:
['Frame#', 'Time', 'Valence/class', 'Valence/probability', 'Imu/MotionIntensity', 'Ppg/QualityIndex']

,Frame#,Time,Valence/class,Valence/probability,Imu/MotionIntensity,Ppg/QualityIndex
0,1,1.703164e+09,0.0,0.415,0.066667,1.0
1,2,1.703164e+09,0.0,0.415,0.066667,1.0
2,3,1.703164e+09,0.0,0.415,0.066667,1.0
3,4,1.703164e+09,0.0,0.415,0.066667,1.0
4,5,1.703164e+09,0.0,0.415,0.066667,1.0

In [16]:
sensor_keywords = [
    "time", "timestamp", "video", "stimulus",
    "event", "segment", "label", "start", "end"
]

for f in sample_files:
    df_sample = read_csv_auto(f, nrows=5)
    
    matching_cols = [
        col for col in df_sample.columns
        if any(k in str(col).lower() for k in sensor_keywords)
    ]
    
    print(f.name, "=>", matching_cols)

3NVLIWA4.csv => []
arousal_3NVLIWA4.csv => ['Time']
breathingRate_3NVLIWA4.csv => ['Time']
emgActivation_3NVLIWA4.csv => ['Time']
expression_3NVLIWA4.csv => ['Time']
facialActivation_3NVLIWA4.csv => ['Time']
facialValence_3NVLIWA4.csv => ['Time']
headMotion_3NVLIWA4.csv => []
hrv_3NVLIWA4.csv => ['Time']
valence_3NVLIWA4.csv => ['Time']

In [31]:
expression_files = sorted(DATA_DIR.rglob("*expression*.csv"))

print("Found expression files:", len(expression_files))

if not expression_files:
    raise FileNotFoundError(f"No expression CSV files found under {DATA_DIR}")

expression_file = expression_files[0]
print("Using expression file:", expression_file.name)

expression_sample = read_csv_auto(expression_file, nrows=50000)
print("Expression sample shape:", expression_sample.shape)
print("Expression columns:", expression_sample.columns.tolist())

if "Expression/Type" in expression_sample.columns:
    expression_types = expression_sample["Expression/Type"].dropna().unique()
    print("Available expression types:")
    print(expression_types)
else:
    possible_expression_cols = [
        col for col in expression_sample.columns
        if any(keyword in str(col).lower() for keyword in ["expression", "type", "emotion"])
    ]
    print("Could not find 'Expression/Type'. Possible expression columns:")
    print(possible_expression_cols)

Found expression files: 106
Using expression file: expression_3NVLIWA4.csv
Expression sample shape: (50000, 4)
Expression columns: ['Frame#', 'Time', 'Expression/Type', 'Expression/Intensity']
Available expression types:
['neutral']

## 6. Expression file inspection

- Find the expression CSV files across all participant folders.
- Load one sample expression file and inspect its columns and expression types.
- This step confirms which expression signal columns are available for later video-level features.

In [33]:
display(expression_sample.head(10))
print(expression_sample.columns.tolist())

   Frame#          Time Expression/Type  Expression/Intensity
0       1  1.703164e+09         neutral                   0.0
1       2  1.703164e+09         neutral                   0.0
2       3  1.703164e+09         neutral                   0.0
3       4  1.703164e+09         neutral                   0.0
4       5  1.703164e+09         neutral                   0.0
5       6  1.703164e+09         neutral                   0.0
6       7  1.703164e+09         neutral                   0.0
7       8  1.703164e+09         neutral                   0.0
8       9  1.703164e+09         neutral                   0.0
9      10  1.703164e+09         neutral                   0.0

['Frame#', 'Time', 'Expression/Type', 'Expression/Intensity']

In [20]:
print(details.columns.tolist())
print(questionnaires.columns.tolist())
display(details.head(10))
display(questionnaires.head(10))

['ID', 'start_cal_time_h', 'start_cal_time_m', 'start_vid_time_h', 'start_vid_time_m', 'end_vid_time_h', 'end_vid_time_m', 'additional info']
['ID', 'gender', 'age', 'slo_fluent', 'epil-hc', 'other_healthcon', 'good_vision', 'bad_hearing', 'facial_palsy-stroke', 'VR_experience', 'current_status', 'degree', 'group_job-sp', 'anxiety', 'inf_cons', 'video', 'feelof_presence_inVE', 'captivatedby_VE', 'real_VWorld', 'awareness_RWorld', 'issues_in_VR', 'stateEmpathy1a', 'stateEmpathy1b', 'stateEmpathy1c', 'valence1', 'arousal1', 'discomfort1', 'stateEmpathy2a', 'stateEmpathy2b', 'stateEmpathy2c', 'valence2', 'arousal2', 'discomfort2', 'stateEmpathy3a', 'stateEmpathy3b', 'stateEmpathy3c', 'valence3', 'arousal3', 'discomfort3', 'stateEmpathy4a', 'stateEmpathy4b', 'stateEmpathy4c', 'valence4', 'arousal4', 'discomfort4', 'stateValence', 'stateArousal', 'perspective-taking_points', 'perspective-taking_rate', 'online-simulation_points', 'online-simulation_rate', 'traitEmpathy_cog_points', 'traitEmpathy_cog_rate', 'emotion-contagion_points', 'emotion-contagion_rate', 'proximal-responsivity_points', 'proximal-responsivity_rate', 'peripheral-responsivity_points', 'peripheral-responsivity_rate', 'traitEmpathy_affec_points', 'traitEmpathy_affec_rate', 'Empathy1', 'Empathy2', 'Empathy3', 'Empathy4', 'Empathy_avg', 'Empathy_min', 'Arousal_RC']

,ID,start_cal_time_h,start_cal_time_m,start_vid_time_h,start_vid_time_m,end_vid_time_h,end_vid_time_m,additional info
0,1,14,1,14,5,14.0,36.0,work
1,2,13,6,13,10,13.0,38.0,work
2,3,14,11,14,15,14.0,35.0,work - without RC vid
3,4,13,9,13,13,13.0,34.0,work
4,5,14,18,14,22,14.0,47.0,work
5,6,14,45,14,48,14.0,NaN,work
6,7,15,15,15,15,NaN,NaN,work
7,8,14,22,14,26,NaN,NaN,work
8,9,15,19,15,22,NaN,NaN,work
9,10,14,27,14,30,NaN,NaN,work

,ID,gender,age,slo_fluent,epil-hc,other_healthcon,good_vision,bad_hearing,facial_palsy-stroke,VR_experience,...,peripheral-responsivity_rate,traitEmpathy_affec_points,traitEmpathy_affec_rate,Empathy1,Empathy2,Empathy3,Empathy4,Empathy_avg,Empathy_min,Arousal_RC
0,1,z,24,1,0,0,1,0,0,3,...,3.50,8.00,3,3.0,1.7,2.7,2.3,2.4,1.7,4.0
1,2,m,27,1,0,0,1,0,0,3,...,2.50,7.00,2,3.0,0.0,1.0,1.7,1.4,0.0,0.0
2,3,m,28,1,0,0,1,0,0,3,...,2.75,8.00,3,1.0,2.7,2.7,1.7,2.0,1.0,NaN
3,4,m,30,1,0,0,1,0,0,1,...,2.75,7.50,2,2.3,3.0,3.0,2.7,2.8,2.3,1.0
4,5,m,35,1,0,0,1,0,0,2,...,2.50,5.50,2,2.3,2.7,3.7,1.3,2.5,1.3,4.0
5,6,z,29,1,0,0,1,0,0,1,...,2.75,5.75,2,3.0,3.7,3.0,3.7,3.3,3.0,2.0
6,7,m,30,1,0,0,0,0,0,3,...,2.50,6.75,2,3.3,1.3,2.3,1.3,2.1,1.3,3.0
7,8,m,32,0,0,0,1,0,0,3,...,2.75,7.75,3,2.3,1.7,2.0,1.3,1.8,1.3,3.0
8,9,z,36,1,0,0,1,0,0,1,...,3.00,6.00,2,3.3,3.7,3.3,2.0,3.1,2.0,4.0
9,10,m,40,1,0,0,1,0,0,3,...,2.50,7.75,3,2.3,1.3,2.7,1.7,2.0,1.3,2.0

In [21]:
#site koloni so brojce
print("DETAILS COLUMNS:")
for i, col in enumerate(details.columns):
    print(i, col)

print("\nQUESTIONNAIRES COLUMNS:")
for i, col in enumerate(questionnaires.columns):
    print(i, col)

DETAILS COLUMNS:
0 ID
1 start_cal_time_h
2 start_cal_time_m
3 start_vid_time_h
4 start_vid_time_m
5 end_vid_time_h
6 end_vid_time_m
7 additional info

QUESTIONNAIRES COLUMNS:
0 ID
1 gender
2 age
3 slo_fluent
4 epil-hc
5 other_healthcon
6 good_vision
7 bad_hearing
8 facial_palsy-stroke
9 VR_experience
10 current_status
11 degree
12 group_job-sp
13 anxiety
14 inf_cons
15 video
16 feelof_presence_inVE
17 captivatedby_VE
18 real_VWorld
19 awareness_RWorld
20 issues_in_VR
21 stateEmpathy1a
22 stateEmpathy1b
23 stateEmpathy1c
24 valence1
25 arousal1
26 discomfort1
27 stateEmpathy2a
28 stateEmpathy2b
29 stateEmpathy2c
30 valence2
31 arousal2
32 discomfort2
33 stateEmpathy3a
34 stateEmpathy3b
35 stateEmpathy3c
36 valence3
37 arousal3
38 discomfort3
39 stateEmpathy4a
40 stateEmpathy4b
41 stateEmpathy4c
42 valence4
43 arousal4
44 discomfort4
45 stateValence
46 stateArousal
47 perspective-taking_points
48 perspective-taking_rate
49 online-simulation_points
50 online-simulation_rate
51 traitEmpathy_cog_points
52 traitEmpathy_cog_rate
53 emotion-contagion_points
54 emotion-contagion_rate
55 proximal-responsivity_points
56 proximal-responsivity_rate
57 peripheral-responsivity_points
58 peripheral-responsivity_rate
59 traitEmpathy_affec_points
60 traitEmpathy_affec_rate
61 Empathy1
62 Empathy2
63 Empathy3
64 Empathy4
65 Empathy_avg
66 Empathy_min
67 Arousal_RC

In [22]:
#barame valence/arousal koloni 
label_keywords = ["valence", "arousal", "val", "aro", "emotion", "empathy"]

print("Possible label columns in questionnaires:")
for col in questionnaires.columns:
    if any(k in col.lower() for k in label_keywords):
        print(col)

Possible label columns in questionnaires:
stateEmpathy1a
stateEmpathy1b
stateEmpathy1c
valence1
arousal1
stateEmpathy2a
stateEmpathy2b
stateEmpathy2c
valence2
arousal2
stateEmpathy3a
stateEmpathy3b
stateEmpathy3c
valence3
arousal3
stateEmpathy4a
stateEmpathy4b
stateEmpathy4c
valence4
arousal4
stateValence
stateArousal
traitEmpathy_cog_points
traitEmpathy_cog_rate
emotion-contagion_points
emotion-contagion_rate
traitEmpathy_affec_points
traitEmpathy_affec_rate
Empathy1
Empathy2
Empathy3
Empathy4
Empathy_avg
Empathy_min
Arousal_RC

In [23]:
print("Possible video/time columns in details:")
for col in details.columns:
    if any(k in col.lower() for k in ["id", "video", "vid", "time", "start", "end", "duration"]):
        print(col)

Possible video/time columns in details:
ID
start_cal_time_h
start_cal_time_m
start_vid_time_h
start_vid_time_m
end_vid_time_h
end_vid_time_m

In [32]:
# koi label koloni imaat missing values
possible_label_cols = [
    col for col in questionnaires.columns
    if any(k in col.lower() for k in ["valence", "arousal", "val", "aro", "empathy"])
]

label_summary = questionnaires[["ID"] + possible_label_cols].copy()

display(label_summary.head(10))

missing_counts = label_summary.isna().sum().tolist()
missing_percent = [round(value * 100, 2) for value in label_summary.isna().mean().tolist()]
unique_values = [label_summary[col].nunique(dropna=True) for col in label_summary.columns]

missing_label_report = pd.DataFrame({
    "column": label_summary.columns,
    "missing_count": missing_counts,
    "missing_percent": missing_percent,
    "unique_values": unique_values
})

display(missing_label_report)

,ID,stateEmpathy1a,stateEmpathy1b,stateEmpathy1c,valence1,arousal1,stateEmpathy2a,stateEmpathy2b,stateEmpathy2c,valence2,...,traitEmpathy_cog_rate,traitEmpathy_affec_points,traitEmpathy_affec_rate,Empathy1,Empathy2,Empathy3,Empathy4,Empathy_avg,Empathy_min,Arousal_RC
0,1,3,3,3,4,3,2,1,2,3,...,1,8.00,3,3.0,1.7,2.7,2.3,2.4,1.7,4.0
1,2,3,3,3,3,3,0,0,0,2,...,3,7.00,2,3.0,0.0,1.0,1.7,1.4,0.0,0.0
2,3,1,1,1,1,3,3,3,2,3,...,2,8.00,3,1.0,2.7,2.7,1.7,2.0,1.0,NaN
3,4,2,2,3,4,2,3,3,3,3,...,2,7.50,2,2.3,3.0,3.0,2.7,2.8,2.3,1.0
4,5,3,1,3,3,3,2,2,4,3,...,2,5.50,2,2.3,2.7,3.7,1.3,2.5,1.3,4.0
5,6,3,2,4,3,2,4,4,3,3,...,1,5.75,2,3.0,3.7,3.0,3.7,3.3,3.0,2.0
6,7,3,3,4,4,2,1,1,2,4,...,3,6.75,2,3.3,1.3,2.3,1.3,2.1,1.3,3.0
7,8,3,3,1,3,1,1,2,2,3,...,2,7.75,3,2.3,1.7,2.0,1.3,1.8,1.3,3.0
8,9,3,3,4,3,3,3,4,4,4,...,2,6.00,2,3.3,3.7,3.3,2.0,3.1,2.0,4.0
9,10,2,2,3,3,2,1,0,3,2,...,2,7.75,3,2.3,1.3,2.7,1.7,2.0,1.3,2.0

                       column  missing_count  missing_percent  unique_values
0                          ID              0             0.00            105
1              stateEmpathy1a              0             0.00              5
2              stateEmpathy1b              0             0.00              5
3              stateEmpathy1c              0             0.00              5
4                    valence1              0             0.00              4
5                    arousal1              0             0.00              5
6              stateEmpathy2a              0             0.00              5
7              stateEmpathy2b              0             0.00              5
8              stateEmpathy2c              0             0.00              5
9                    valence2              0             0.00              3
10                   arousal2              0             0.00              4
11             stateEmpathy3a              0             0.00              4
12             stateEmpathy3b              0             0.00              5
13             stateEmpathy3c              0             0.00              5
14                   valence3              0             0.00              5
15                   arousal3              0             0.00              5
16             stateEmpathy4a              0             0.00              5
17             stateEmpathy4b              0             0.00              5
18             stateEmpathy4c              0             0.00              5
19                   valence4              0             0.00              4
20                   arousal4              0             0.00              5
21               stateValence              1             0.95              5
22               stateArousal              1             0.95              5
23    traitEmpathy_cog_points              0             0.00             78
24      traitEmpathy_cog_rate              0             0.00              3
25  traitEmpathy_affec_points              0             0.00             15
26    traitEmpathy_affec_rate              0             0.00              2
27                   Empathy1              0             0.00             12
28                   Empathy2              0             0.00             12
29                   Empathy3              0             0.00             11
30                   Empathy4              0             0.00             13
31                Empathy_avg              0             0.00             23
32                Empathy_min              0             0.00             11
33                 Arousal_RC              1             0.95              5

## 7. Missing values and dataset completeness

- Check which label-related columns contain missing values.
- Summarize how complete the questionnaires table is for the label columns.
- Compare folder IDs with table IDs to confirm dataset consistency and completeness.

In [25]:
folder_ids = sorted([extract_participant_id(p.name) for p in participant_dirs])
details_ids = sorted(details["ID"].dropna().astype(int).unique())
questionnaire_ids = sorted(questionnaires["ID"].dropna().astype(int).unique())

print("Participant folders:", len(folder_ids), folder_ids[:5], folder_ids[-5:])
print("Details IDs:", len(details_ids), details_ids[:5], details_ids[-5:])
print("Questionnaire IDs:", len(questionnaire_ids), questionnaire_ids[:5], questionnaire_ids[-5:])

print("Folders not in details:", sorted(set(folder_ids) - set(details_ids)))
print("Folders not in questionnaires:", sorted(set(folder_ids) - set(questionnaire_ids)))

print("Questionnaires not in folders:", sorted(set(questionnaire_ids) - set(folder_ids)))
#so rezulattot e dokazano deka participant_id = brojot od imeto na folderot, samo eden participant ima dva folderi S

Participant folders: 106 [1, 2, 3, 4, 5] [101, 102, 103, 104, 105]
Details IDs: 105 [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)] [np.int64(101), np.int64(102), np.int64(103), np.int64(104), np.int64(105)]
Questionnaire IDs: 105 [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)] [np.int64(101), np.int64(102), np.int64(103), np.int64(104), np.int64(105)]
Folders not in details: []
Folders not in questionnaires: []
Questionnaires not in folders: []

In [ ]:
# video / stimulus summary i  compact dataset overview
video_keywords = ["video", "stimulus", "clip", "movie", "scene", "trial"]
video_id_candidates = [
    col for col in details.columns
    if any(keyword in str(col).lower() for keyword in video_keywords)
]

time_candidates = [
    col for col in details.columns
    if any(keyword in str(col).lower() for keyword in ["start", "end", "duration", "time", "timestamp"])
]

print("Possible video/stimulus columns in details:")
print(video_id_candidates)
print("Possible time columns in details:")
print(time_candidates)

summary_columns = video_id_candidates + [col for col in time_candidates if col not in video_id_candidates]
if summary_columns:
    video_summary = pd.DataFrame({
        "column": summary_columns,
        "missing_count": [int(details[col].isna().sum()) for col in summary_columns],
        "unique_values": [int(details[col].nunique(dropna=True)) for col in summary_columns],
        "sample_values": [details[col].dropna().astype(str).head(3).tolist() for col in summary_columns],
    })
    display(video_summary)
else:
    print("No obvious video/stimulus/time columns found in details.")

sensor_columns_found = []
if sample_files:
    first_sensor_sample = read_csv_auto(sample_files[0], nrows=5)
    sensor_columns_found = [
        col for col in first_sensor_sample.columns
        if any(keyword in str(col).lower() for keyword in sensor_keywords)
    ]

summary_table = pd.DataFrame([
    {"item": "participant_folders", "value": len(participant_dirs)},
    {"item": "details_rows", "value": len(details)},
    {"item": "questionnaires_rows", "value": len(questionnaires)},
    {"item": "top_level_csv_files", "value": len(top_level_csvs)},
    {"item": "expression_files", "value": len(expression_files)},
    {"item": "label_columns", "value": len(possible_label_cols)},
    {"item": "sensor_columns_found", "value": len(sensor_columns_found)},
])

display(summary_table)

Possible video/stimulus columns in details:
[]
Possible time columns in details:
['start_cal_time_h', 'start_cal_time_m', 'start_vid_time_h', 'start_vid_time_m', 'end_vid_time_h', 'end_vid_time_m']

             column  missing_count  unique_values       sample_values
0  start_cal_time_h              0              8        [14, 13, 14]
1  start_cal_time_m              0             43          [1, 6, 11]
2  start_vid_time_h              0              8        [14, 13, 14]
3  start_vid_time_m              0             43         [5, 10, 15]
4    end_vid_time_h              6              8  [14.0, 13.0, 14.0]
5    end_vid_time_m              7             44  [36.0, 38.0, 35.0]

                   item  value
0   participant_folders    106
1          details_rows    105
2   questionnaires_rows    105
3   top_level_csv_files      2
4      expression_files    106
5         label_columns     33
6  sensor_columns_found      9

## Initial Dataset Structure

The dataset is organized around participant folders inside `data3/`.

- `final_data_details.csv` contains participant-level and session-level metadata.
- `final_data_questionnaires.csv` contains questionnaire and label-related variables such as valence, arousal, and empathy measures.
- The per-participant CSV files inside each participant folder contain time-based sensor or annotation data, including expression, facial, breathing, and activation signals.

From the checks above, the dataset appears consistent in participant IDs, and the main columns for labels, sensors, timestamps, and video/stimulus references have been identified.

### What this notebook now covers

- participant summary
- video/stimulus summary
- available label columns
- available sensor columns
- missing value report
- initial dataset structure explanation